### ISSUE TITLE
HTTP connections do not work

### ISSUE THREAD

**Issue by darlexlin** [snegov/docker-seafile-client#1]
I'm using http service , and the port is 80 
but docker return to me:
requests.exceptions.SSLError: HTTPSConnectionPool(host='172.20.0.110', port=80): Max retries exceeded with url: /api2/auth-token/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

**Comment by irrelevant-cookie** [comment]
Thank you for your input. It is a bug indeed caused by hardcoded https:// scheme. Will be fixed in 0.0.4.
